[package]
name = "reward_pool"
edition = "2024.beta"
license = "MIT"
authors = ["Studio Mirai, LLC (build@sm.xyz)"]

[dependencies]
stake = { local = "../stake" }

[environments]
mirainet = "f1eb94c0"