[package]
name = "reward_pool"
edition = "2024"
license = "MIT"
authors = ["Unconfirmed Labs, LLC (os@unconfirmed.com)"]

[dependencies]
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "main" }
stake = { git = "https://github.com/unconfirmedlabs/stake.git", rev = "main" }